### ISSUE TITLE
Core Data

### ISSUE THREAD

**Issue by Jaimin9998** [abhi-dave/helloworld#1]

**Comment by abhiperry** [comment]
@Jaimin9998 1 element hato a pan nathi aavto have !!

**Comment by Jaimin9998** [comment]
ha to problem json ma hase
json mathi elecid ma value nai jati hoy check kari jo

**Comment by Jaimin9998** [comment]
problem core data no nathi elecID ni value nil malti hase

**Comment by Jaimin9998** [comment]
is it solved 
reply??

**Comment by abhiperry** [comment]
```
JSON Data [
  {
    "elecid" : "157",
    "subname" : "Python Programming",
    "subacr" : "PP",
    "subcredit" : "5",
    "sublink" : "http:\/\/192.168.0.101\/newAttempt\/syllabus\/2180711.pdf",
    "subcode" : "2180711",
    "subtype" : "Elective"
  }
]
```

JSON DATA Toh aave j chhe

**Comment by abhiperry** [comment]
@Jaimin9998  
bhai thai gayu hu
khoti jagya a call karvato hato SAVEDATA

**Comment by abhiperry** [comment]
@Jaimin9998 
DONE!! 
Both electives and Primary Subjects are fetched in the view!

**Comment by Jaimin9998** [comment]
File 1 : View Controller code
//
//  ViewController.swift
//  Test
//
//  Created by Jaimin Galiya on 06/03/17.
//  Copyright © 2017 Jaimin Galiya. All rights reserved.
//

import UIKit

class ViewController: UIViewController, UIPopoverPresentationControllerDelegate {

   
    let picker = UIImageView(image: UIImage(named: "picker"))
    
    struct properties {
        static let moods = [
            ["title" : "Student", "color" : "#8647b7"],
            ["title" : "Parent", "color": "#4870b7"],
            ["title" : "Admin", "color" : "#45a85a"],
            ["title" : "Guest", "color" : "#a8a23f"]
        ]
    }

    @IBAction func txtActionValueChange(_ sender: AnyObject) {
        textData = txtValues.text!
    }
    
    @IBAction func btnActionTap(_ sender: AnyObject) {
        picker.isHidden ? openPicker() : closePicker()
    }
    
    func createPicker()
    {
        picker.frame = CGRect(x: ((self.view.frame.width / 2) - 143), y: 200, width: 286, height: 291)
        picker.alpha = 0
        picker.isHidden = true
        picker.isUserInteractionEnabled = true
        
        var offset = 21
        
        for (index, feeling) in properties.moods.enumerated()
        {
            let button = UIButton()
            button.frame = CGRect(x: 13, y: offset, width: 260, height: 43)
            button.setTitleColor(UIColor(rgba: feeling["color"]!), for: UIControlState())
            button.setTitle(feeling["title"], for: UIControlState())
            button.tag = index
            
            picker.addSubview(button)
            
            offset += 44
        }
        
        view.addSubview(picker)
    }

    
    func openPicker()
    {
        self.picker.isHidden = false
        
        UIView.animate(withDuration: 0.3,
                       animations: {
                        self.picker.frame = CGRect(x: ((self.view.frame.width / 2) - 143), y: 230, width: 286, height: 291)
                        self.picker.alpha = 1
        })
    }
    
    func closePicker()
    {
        UIView.animate(withDuration: 0.3,
                       animations: {
                        self.picker.frame = CGRect(x: ((self.view.frame.width / 2) - 143), y: 200, width: 286, height: 291)
                        self.picker.alpha = 0
            },
                       completion: { finished in
                        self.picker.isHidden = true
            }
        )
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        lblValues.text = txtValues.text
        createPicker()
        // Do any additional setup after loading the view, typically from a nib.
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    func adaptivePresentationStyle(for controller: UIPresentationController) -> UIModalPresentationStyle
    {
        return UIModalPresentationStyle.none
    }
}


File 2 : UIColor.swift

import UIKit

extension UIColor
{
  convenience init(rgba: String)
  {
    var red:   CGFloat = 0.0
    var green: CGFloat = 0.0
    var blue:  CGFloat = 0.0
    var alpha: CGFloat = 1.0
    
    if rgba.hasPrefix("#")
    {
      let index   = rgba.characters.index(rgba.startIndex, offsetBy: 1)
      let hex     = rgba.substring(from: index)
      let scanner = Scanner(string: hex)
      var hexValue: CUnsignedLongLong = 0
      
      if scanner.scanHexInt64(&hexValue)
      {
        if hex.characters.count == 6
        {
          red   = CGFloat((hexValue & 0xFF0000) >> 16) / 255.0
          green = CGFloat((hexValue & 0x00FF00) >> 8)  / 255.0
          blue  = CGFloat(hexValue & 0x0000FF) / 255.0
        }
        else if hex.characters.count == 8
        {
          red   = CGFloat((hexValue & 0xFF000000) >> 24) / 255.0
          green = CGFloat((hexValue & 0x00FF0000) >> 16) / 255.0
          blue  = CGFloat((hexValue & 0x0000FF00) >> 8)  / 255.0
          alpha = CGFloat(hexValue & 0x000000FF)         / 255.0
        }
        else
        {
          print("invalid rgb string, length should be 7 or 9", terminator: "")
        }
      }
      else
      {
        print("scan hex error", terminator: "")
      }
    }
    else
    {
      print("invalid rgb string, missing '#' as prefix", terminator: "")
    }
    
    self.init(red:red, green:green, blue:blue, alpha:alpha)
  }
}

**Comment by Jaimin9998** [comment]
take one button and connect it with buttonActionTap

**Comment by Jaimin9998** [comment]
//Updated ERPCoreData Code
//Added Student Current details to core data
//  ViewController.swift
//  ERPCoreData
//
//  Created by Jaimin V Galiya on 02/03/17.
//  Copyright © 2017 Jaimin V Galiya. All rights reserved.
//

import UIKit
import Alamofire
import SwiftyJSON
import CoreData

class ViewController: UIViewController {

    @IBOutlet weak var txtSemId: UITextField!
    @IBOutlet weak var txtBranchId: UITextField!
    @IBOutlet var dataView: UIView!
    @IBOutlet weak var txtEnrollment: UITextField!
    var json: AnyObject?
    var enrollment: String = ""
    var student: [NSManagedObject] = []
    var name: String = ""
    var bloodGrp: String = ""
    var std_type: String = ""
    var local_addr: String = ""
    var perm_addr: String = ""
    var std_mob1: String = ""
    var std_mob2: String = ""
    var res_contact: String = ""
    var gender: String = ""
    var admit_date: String = ""
    var std_dob: String = ""
    var photo: String = ""
    var email: String = ""
    var elecID: [String] = []
    var elsubCode: [String] = []
    var elsubName: [String] = []
    var elsubAcr: [String] = []
    var elsubCredit: [String] = []
    var elsubType: [String] = []
    var elsubLink: [String] = []
    var sub_code: [String] = []
    var sub_name: [String] = []
    var sub_acr: [String] = []
    var sub_credit: [String] = []
    var sub_type: [String] = []
    var sub_link: [String] = []
    var dis_id: String = ""
    var dis_name: String = ""
    var branch_id: String = ""
    var branch_code: String = ""
    var branch_name: String = ""
    var sem_id: String = ""
    var sem_no: String = ""
    var div_id: String = ""
    var div_name: String = ""
    var batch_id: String = ""
    var batch_name: String = ""
    let context = (UIApplication.shared.delegate as! AppDelegate).persistentContainer.viewContext
    override func viewDidLoad() {
        super.viewDidLoad()
        print(context)
        // Do any additional setup after loading the view, typically from a nib.
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }

    @IBAction func btnActionSaveData(_ sender: Any) {
        enrollment = txtEnrollment.text!
        AlamofireActivity()
        //deleteAllData(entity: "Student_Profile")
        //deleteAllData(entity: "Subject_Elective")
        //deleteAllData(entity: "Subject_Details")
        //saveData()
    }

    @IBAction func btnActionGetData(_ sender: Any) {
        getData()
    }
    
    func AlamofireActivity(){
        //let urlString =  "http://192.168.191.1/ERP_API/F1profile.php"
        //Alamofire.request(urlString,method: .post, parameters: requestParams, encoding: JSONEncoding.default, headers: [:])
        Alamofire.request("http://192.168.191.1/ERP_API/F1profile.php", method: .post, parameters: ["enroll": enrollment]).responseJSON { response in
            self.json = response.result.value as AnyObject?
            //  print(self.json)
            let json1 = JSON(self.json as Any)
            print(json1.count)
            print(json1)
            self.name = json1[0]["fname"].stringValue + " " + json1[0]["mname"].stringValue + " " + json1[0]["lname"].stringValue
            self.bloodGrp = json1[0]["bgrp"].stringValue
            self.local_addr = json1[0]["lstr"].stringValue + " " + json1[0]["larea"].stringValue + " " + json1[0]["lcity"].stringValue + " " + json1[0]["lpin"].stringValue
            self.perm_addr = json1[0]["pstr"].stringValue + " " + json1[0]["parea"].stringValue + " " + json1[0]["pcity"].stringValue + " " + json1[0]["ppin"].stringValue
            self.email = json1[0]["mail"].stringValue
            self.std_mob1 = json1[0]["mob1"].stringValue
            self.std_mob2 = json1[0]["mob2"].stringValue
            self.gender = json1[0]["gender"].stringValue
            self.std_dob = json1[0]["dob"].stringValue
            self.admit_date = json1[0]["jdate"].stringValue
            self.std_type = json1[0]["stdtype"].stringValue
            self.res_contact = json1[0]["rescon"].stringValue
            self.photo = json1[0]["photo"].stringValue
        }
        Alamofire.request("http://192.168.191.1/ERP_API/F1studElective.php", method: .post, parameters: ["enroll": enrollment]).responseJSON { response in
            self.json = response.result.value as AnyObject?
            //  print(self.json)
            let json1 = JSON(self.json as Any)
            print("JSON Data \(json1)")
            for i in 0..<json1.count{
            self.elecID.append(json1[i]["elecid"].stringValue)
            self.elsubCode.append(json1[i]["subcode"].stringValue)
            self.elsubName.append(json1[i]["subname"].stringValue)
            self.elsubAcr.append(json1[i]["subacr"].stringValue)
            self.elsubCredit.append(json1[i]["subcredit"].stringValue)
            self.elsubType.append(json1[i]["subtype"].stringValue)
            self.elsubLink.append(json1[i]["sublink"].stringValue)
                print(self.elecID)
            }
        }
        Alamofire.request("http://192.168.191.1/ERP_API/F1studentSyllabus.php", method: .post, parameters: ["bcode": txtBranchId.text!, "scode": txtSemId.text!]).responseJSON { response in
            self.json = response.result.value as AnyObject?
            //  print(self.json)
            let json1 = JSON(self.json as Any)
            print("JSON Data \(json1)")
            for i in 0..<json1.count{
                self.sub_code.append(json1[i]["subcode"].stringValue)
                self.sub_name.append(json1[i]["subname"].stringValue)
                self.sub_acr.append(json1[i]["subacr"].stringValue)
                self.sub_credit.append(json1[i]["subcredit"].stringValue)
                self.sub_type.append(json1[i]["subtype"].stringValue)
                self.sub_link.append(json1[i]["sublink"].stringValue)
            }
            print(self.sub_code)
        }
        Alamofire.request("http://192.168.191.1/ERP_API/F1studCurrent.php", method: .post, parameters: ["Enrol": enrollment]).responseJSON { response in
            self.json = response.result.value as AnyObject?
            //  print(self.json)
            let json1 = JSON(self.json as Any)
            print(json1.count)
            print(json1)
            self.dis_id = json1[0]["disid"].stringValue
            self.dis_name = json1[0]["disname"].stringValue
            self.branch_id = json1[0]["brid"].stringValue
            self.branch_code = json1[0]["brcode"].stringValue
            self.branch_name = json1[0]["brname"].stringValue
            self.sem_id = json1[0]["semid"].stringValue
            self.sem_no = json1[0]["semno"].stringValue
            self.div_id = json1[0]["divid"].stringValue
            self.div_name = json1[0]["divname"].stringValue
            self.batch_id = json1[0]["batid"].stringValue
            self.batch_name = json1[0]["batname"].stringValue
        }
        deleteAllData(entity: "Student_Profile")
        deleteAllData(entity: "Subject_Elective")
        deleteAllData(entity: "Subject_Details")
        deleteAllData(entity: "Student_Current")
        saveData()
    }
    
    func saveData(){
        //Select Student Profile
        let entity =  NSEntityDescription.entity(forEntityName: "Student_Profile", in: context)
        let stud = NSManagedObject(entity: entity!, insertInto: context)
        
        //Select Student Current Details
        let studCurrentEntity = NSEntityDescription.entity(forEntityName: "Student_Current", in: context)
        let studCurrent = NSManagedObject(entity: studCurrentEntity!, insertInto: context)
        
        
        //setValues of Profile
        stud.setValue(enrollment, forKey: "enrollment")
        stud.setValue(name, forKey: "std_name")
        stud.setValue(local_addr, forKey: "std_local_address")
        stud.setValue(perm_addr, forKey: "std_per_address")
        stud.setValue(gender, forKey: "std_gender")
        stud.setValue(email, forKey: "std_email")
        stud.setValue(std_mob1, forKey: "std_mob1")
        stud.setValue(std_mob2, forKey: "std_mob2")
        stud.setValue(res_contact, forKey: "std_res_contact")
        stud.setValue(std_type, forKey: "std_type")
        stud.setValue(admit_date, forKey: "std_admit_date")
        stud.setValue(bloodGrp, forKey: "std_bldgrp")
        stud.setValue(photo, forKey: "std_photo")
        stud.setValue(std_dob, forKey: "std_dob")
        
        //set values of elective subject
        for i in 0..<elecID.count{
            let elsub = NSEntityDescription.insertNewObject(forEntityName: "Subject_Elective", into: context)
            //let elsub = NSManagedObject(entity: entity1!, insertInto: context)
            print(elecID[i])
            elsub.setValue(elecID[i], forKey: "elec_id")
            elsub.setValue(elsubName[i], forKey: "elec_sub_name")
            elsub.setValue(elsubAcr[i], forKey: "elec_sub_acr")
            elsub.setValue(elsubCode[i], forKey: "elec_sub_code")
            elsub.setValue(elsubCredit[i], forKey: "elec_sub_credit")
            elsub.setValue(elsubType[i], forKey: "elec_sub_type")
            elsub.setValue(elsubLink[i], forKey: "elec_sub_link")
            //Subject_Elective.
            do {
                try context.save()
                print("elective saved!")
            } catch let error as NSError  {
                print("Could not save \(error), \(error.userInfo)")
            }
        }
        
        //set values of subject
        for i in 0..<sub_code.count{
            let sub = NSEntityDescription.insertNewObject(forEntityName: "Subject_Details", into: context)
            //let sub = NSManagedObject(entity: subEntity!, insertInto: context)
            sub.setValue(sub_code[i], forKey: "sub_code")
            sub.setValue(sub_name[i], forKey: "sub_name")
            sub.setValue(sub_acr[i], forKey: "sub_acr")
            sub.setValue(sub_credit[i], forKey: "sub_credit")
            sub.setValue(sub_type[i], forKey: "sub_type")
            sub.setValue(sub_link[i], forKey: "sub_link")
            //Subject_Details.append(sub)
            do {
                try context.save()
                print("subject saved!")
            } catch let error as NSError  {
                print("Could not save \(error), \(error.userInfo)")
            }
        }
        
        //set values of student current details
        studCurrent.setValue(dis_id, forKey: "dis_id")
        studCurrent.setValue(dis_name, forKey: "dis_name")
        studCurrent.setValue(branch_id, forKey: "branch_id")
        studCurrent.setValue(branch_name, forKey: "branch_name")
        studCurrent.setValue(branch_code, forKey: "branch_code")
        studCurrent.setValue(sem_id, forKey: "sem_id")
        studCurrent.setValue(sem_no, forKey: "sem_no")
        studCurrent.setValue(div_id, forKey: "div_id")
        studCurrent.setValue(div_name, forKey: "div_name")
        studCurrent.setValue(batch_id, forKey: "batch_id")
        studCurrent.setValue(batch_name, forKey: "batch_name")
        
        //save data to entity
        do {
            try context.save()
            print("saved!")
        } catch let error as NSError  {
            print("Could not save \(error), \(error.userInfo)")
        } catch {
            
        }
    }
    
    func getData(){
        //Fetch req with entity name
        let fetchProfile: NSFetchRequest<Student_Profile> = Student_Profile.fetchRequest()
        let fetchElSub: NSFetchRequest<Subject_Elective> = Subject_Elective.fetchRequest()
        let fetchSub: NSFetchRequest<Subject_Details> = Subject_Details.fetchRequest()
        let fetchStudCurrent: NSFetchRequest<Student_Current> = Student_Current.fetchRequest()
        
        do {
            //get data
            let searchProfile = try context.fetch(fetchProfile)
            let searchElSub = try context.fetch(fetchElSub)
            let searchSub = try context.fetch(fetchSub)
            let searchStudCurrent = try context.fetch(fetchStudCurrent)
            
            //check rows
            print ("num of profile result = \(searchProfile.count)")
            print ("num of elective sub = \(searchElSub.count)")
            print ("num of sub = \(searchSub.count)")
            print ("num of Student Current Entry = \(searchStudCurrent.count)")
            var i = 1
            //get and store data where you want
            for stud in searchProfile as [NSManagedObject] {
                //print data
                let getMainViewX = dataView.frame.origin.x
                
                let label = UILabel(frame: CGRect(x: getMainViewX, y: CGFloat(i) * 21, width: 200, height: 21))
                label.textAlignment = .center
                label.text = stud.value(forKey: "enrollment") as! String?
                self.view.addSubview(label)
                print("\(stud.value(forKey: "enrollment"))")
                i += 1
            }
            for elsub in searchElSub as [NSManagedObject]{
                print("Elective Data : \(elsub.value(forKey: "elec_id"))")
            }
            for sub in searchSub as [NSManagedObject]{
                print("Subject Data : \(sub.value(forKey: "sub_code"))")
            }
            for stdCur in searchStudCurrent as [NSManagedObject]{
                print("Student Current Details : \(stdCur.value(forKey: "branch_id"))\(stdCur.value(forKey: "dis_name"))")
            }
        } catch {
            print("Error with request: \(error)")
        }
    }
    
    func deleteAllData(entity: String)
    {
        
        let fetchRequest = NSFetchRequest<NSFetchRequestResult>(entityName: entity)
        fetchRequest.returnsObjectsAsFaults = false
        
        do
        {
            let results = try context.fetch(fetchRequest)
            for managedObject in results
            {
                let managedObjectData:NSManagedObject = managedObject as! NSManagedObject
                context.delete(managedObjectData)
            }
        } catch let error as NSError {
            print("Detele all data in \(entity) error : \(error) \(error.userInfo)")
        }
    }
}

**Comment by Jaimin9998** [comment]
Create One Entity in ERPCoreData.xcdatamodelId

Entity Name : Student_Current
Fields
    dis_id: String?
    dis_name: String?
    branch_id: String?
    branch_name: String?
    branch_code: String?
    var sem_id: String?
    sem_no: String?
    var div_id: String?
    div_name: String?
    batch_id: String?
    batch_name: String?

**Comment by abhiperry** [comment]
Thai Jashe! Done!! Tu aaje pan Office gayo la.. ghare rahevay nee!
